import createError from "http-errors";
import SubCategoryService from "../services/subCategory.service.js";
const model = "sub category";
const Model = "Sub Category";
const SubCategoryController = {
  getAll: async (req, res, next) => {
    try {
      console.log("get all sub category");
      const filter = req.query;
      await SubCategoryService.addData();
      //await SubCategoryService.addData1();
      //await SubCategoryService.addData2();
      //await SubCategoryService.addData3();
      //await SubCategoryService.addData4();
      //await SubCategoryService.addData5();
      //await SubCategoryService.addData6();
      //await SubCategoryService.addData7();
      //await SubCategoryService.addData8();
      //await SubCategoryService.addData9();
      const list = await SubCategoryService.getAll(filter, "");
      if (!list) {
        return next(createError.BadRequest(Model + " list not found"));
      }
      res.json({
        message: "Get " + model + " list successfully",
        status: 200,
        data: list,
      });
    } catch (error) {
      next(createError.InternalServerError(error.message));
    }
  },

  getById: async (req, res, next) => {
    try {
      const { id } = req.params;
      const object = await SubCategoryService.getById(id);
      if (!object) {
        return next(createError.BadRequest(Model + " not found"));
      }
      res.json({
        message: "Get" + model + "successfully",
        status: 200,
        data: object,
      });
    } catch (error) {
      next(createError.InternalServerError(error.message));
    }
  },

  create: async (req, res, next) => {
    try {
      const data = req.body;
      const object = await SubCategoryService.create(data);
      if (!object) {
        return next(createError.BadRequest("Bad request!"));
      }
      res.json({
        message: "Create" + model + "successfully",
        status: 200,
        data: object,
      });
    } catch (error) {
      next(createError.InternalServerError(error.message));
    }
  },
  update: async (req, res, next) => {
    try {
      const data = req.body;
      const { id } = req.params;
      const object = await SubCategoryService.update(id, data);
      if (!object) {
        return next(createError.BadRequest(Model + " not found"));
      }
      res.json({
        message: "Update" + model + "successfully",
        status: 200,
        data: object,
      });
    } catch (error) {
      next(createError.InternalServerError(error.message));
    }
  },

  delete: async (req, res, next) => {
    try {
      const { id } = req.params;
      const object = await SubCategoryService.delete(id);
      if (!object) {
        return next(createError.BadRequest(Model + " not found"));
      }
      res.json({
        message: "Delete" + model + "successfully",
        status: 200,
        data: object,
      });
    } catch (error) {
      next(createError.InternalServerError(error.message));
    }
  },
};

export default SubCategoryController;
